name: Run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fedora_40:
    runs-on: ubuntu-latest
    container: fedora:40
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        dnf install -y \
            @development-tools cmake cmake-gui \
            vtk vtk-qt vtk-devel
    - name: Upload files as artifacts as requested
      uses: actions/upload-artifact@v3
      with:
        name: vtk-module-find-packages
        path: /usr/lib64/cmake/vtk/*-vtk-module-find-packages.cmake
    - name: Build code
      run: sh run_test.sh
      shell: bash
      